# Generated by Django 4.1.4 on 2023-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csrftoken',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Создан'), (1, 'В работе'), (2, 'Доставлен')], default=0),
        ),
    ]
