# Generated by Django 4.1.4 on 2023-01-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Временный'), (1, 'Создан'), (2, 'В работе'), (3, 'Доставлен'), (4, 'Отменен')], default=0),
        ),
    ]
