# Generated by Django 4.1.4 on 2022-12-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=75, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование продукта')),
                ('shot_height', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Высота выстрела (м)')),
                ('time_work', models.PositiveIntegerField(null=True, verbose_name='Время работы (сек)')),
                ('number_of_charges', models.PositiveIntegerField(null=True, verbose_name='Количество зарядов (шт)')),
                ('caliber', models.PositiveIntegerField(null=True, verbose_name='Калибр (мм)')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=15, verbose_name='Артикул')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=75, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('on_sale', models.BooleanField(default=False, verbose_name='В продаже')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Категория')),
                ('characteristic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.feature', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
